COINS = {
    'BTC':'Bitcoin',
    'ETH':'Ethereum',
    'LTC':'Litecoin',
    'EOS':'Ethereum',
    'BNB':'BNB',
    'SOL':'Solana',
    'XRP':'XRP',
    'DOGE':'Dogecoin',
    'ADA': 'Cardano',
    'SHIB': 'SHIBA INU',
    'WBTC': 'Wrapped Bitcoin',
    'AVAX': 'Avalanche',
    'BCH': 'Bitcoin Cash',
    'LINK': 'ChainLink',
    'DOT': 'Polkadot',
    'SUI': 'Sui',
    'DAI': 'Dai',
    'NEAR': 'NEAR Protocol',
    'APT': 'Aptos',
    'UNI': 'Uniswap',
    'WBETH': 'Wrapped Beacon ETH',
    'PEPE': 'Pepe',
    'ICP': 'Internet Computer',
    'TAO': 'Bittensor',
    'FET': 'Artificial Superintelligence Alliance',
    'XLM': 'Stellar Lumens'
}